import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/educacao">
          <a>Educação</a>
        </Link>
        <Link href="/coletas">
          <a>Coletas</a>
        </Link>
        <Link href="/denuncia">
          <a>Denúncia</a>
        </Link>
        <Link href="/avaliacao">
          <a>Avaliação</a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Potiguares
        </a>
      </footer>
    </div>
  )
}
